### ISSUE TITLE
`-enable-cffobf` crashing on VS2022 clang-cl

### ISSUE THREAD

**Issue by robertoaraujom** [61bcdefg/Hikari-LLVM15#55] opened 2023-04-02 20:58 UTC
```
17:46:14:199	1>Running ControlFlowFlattening On ?CityHash64WithSeeds@CityHash@@YA_KPEBDI_K1@Z
17:46:14:199	1>Running ControlFlowFlattening On ?CityHash128WithSeed@CityHash@@YA?AU_uint128@1@PEBDIU21@@Z
17:46:14:199	1>Fixing Stack
17:46:14:199	1>Fixed Stack
17:46:14:199	1>Running ControlFlowFlattening On ?CityMurmur@CityHash@@YA?AU_uint128@1@PEBDIU21@@Z
17:46:14:199	1>Fixing Stack
17:46:14:199	1>Fixed Stack
17:46:14:199	1>Running ControlFlowFlattening On ?CityHash128@CityHash@@YA?AU_uint128@1@PEBDI@Z
17:46:14:199	1>Fixing Stack
17:46:14:199	1>Fixed Stack
17:46:14:199	1>Running ControlFlowFlattening On ?UNALIGNED_LOAD64@CityHash@@YA_KPEBD@Z
17:46:14:199	1>Running ControlFlowFlattening On ?RotateByAtLeast1@CityHash@@YA_K_KH@Z
17:46:14:199	1>Running ControlFlowFlattening On ?Fetch32@CityHash@@YAIPEBD@Z
17:46:14:199	1>Running ControlFlowFlattening On ?UNALIGNED_LOAD32@CityHash@@YAIPEBD@Z
17:46:14:199	1>Running ControlFlowFlattening On ?Hash128to64@CityHash@@YA_KU_uint128@1@@Z
17:46:14:199	1>Doing Post-Run Cleanup
17:46:14:199	1>Hikari Out
17:46:14:199	1>Spend Time: 0.0010576s
17:46:14:274	1>Instruction does not dominate all uses!
17:46:14:274	1>  %mul1 = mul i64 %call, -5435081209227447693, !dbg !338
17:46:14:274	1>  %add6 = add i64 %mul1, %cond.reg2mem.0, !dbg !342
17:46:14:274	1>in function ?CityMurmur@CityHash@@YA?AU_uint128@1@PEBDIU21@@Z
17:46:14:337	1>fatal error: error in backend: Broken function found, compilation aborted!
17:46:14:337	1>PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
17:46:14:337	1>Stack dump:
17:46:14:337	1>0.	Program arguments: D:\\Projetos\\LLVMs\\iz-llvm\\install-llvm\\bin\\clang-cl.exe -cc1 -triple x86_64-pc-windows-msvc19.29.30148 -emit-obj -mincremental-linker-compatible --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name CityHashNusov.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -relaxed-aliasing -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -mllvm -x86-asm-syntax=intel -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -D_MT -flto-visibility-public-std -D_VC_NODEFAULTLIB -fno-rtti-data -fcxx-exceptions -fexceptions -fms-volatile -fdiagnostics-format msvc -gno-column-info -gcodeview -debug-info-kind=constructor "-fcoverage-compilation-dir=%MYPATHREMOVE%" -resource-dir D:\\Projetos\\LLVMs\\iz-llvm\\install-llvm\\lib\\clang\\15.0.7 -I "D:%MYPATHREMOVE%\\src\\" -I D:\\vcpkg\\installed\\x64-windows-static\\include -D NDEBUG -D NODEBUG -D _CONSOLE -D "TARGETNAME=\"%REMOVED%\"" -D WINVER=0x0601 -D _WIN32_WINNT=0x0601 -D _HAS_STATIC_RTTI=0 -D _WINDLL -D _UNICODE -D UNICODE -U _CPPRTTI -U __cpp_rtti -internal-isystem D:\\Projetos\\LLVMs\\iz-llvm\\install-llvm\\lib\\clang\\15.0.7\\include -internal-isystem "../../../%REMOVED%/includes" -internal-isystem "../../../%REMOVED%/src" -internal-isystem D:\\Projetos\\LLVMs\\iz-llvm\\install-llvm\\lib\\clang\\15.0.7\\include -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\atlmfc\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\VS\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\cppwinrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8.1\\Include\\um" -internal-isystem D:\\vcpkg\\installed\\x64-windows-static\\include -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\atlmfc\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\VS\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\cppwinrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8.1\\Include\\um" -internal-isystem D:\\vcpkg\\installed\\x64-windows-static\\include -O2 -Wall -Wno-error -fdeprecated-macro "-fdebug-compilation-dir=%MYPATHREMOVE%" -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.29.30148 -std=c++20 -fdelayed-template-parsing -fno-inline -fno-implicit-modules -fno-caret-diagnostics -vectorize-loops -vectorize-slp -mllvm -enable-cffobf -faddrsig "-object-file-name=%MYPATHREMOVE%\\Publish\\CityHashNusov.obj" -o Publish\\CityHashNusov.obj -x c++ "%MYPATHREMOVE%\\src\\CityHashNusov.cpp"
17:46:14:337	1>1.	<eof> parser at end of file
17:46:14:337	1>2.	Code generation
17:46:14:337	1>3.	Running pass 'Function Pass Manager' on module '%REMOVED%\CityHashNusov.cpp'.
17:46:14:337	1>4.	Running pass 'Module Verifier' on function '@"?CityMurmur@CityHash@@YA?AU_uint128@1@PEBDIU21@@Z"'
17:46:14:337	1>clang-cl : error : clang frontend command failed with exit code 70 (use -v to see invocation)
17:46:14:337	1>clang version 15.0.7 (llvm.git 5ce0346f8b0bd08dfa12f5c598122ee482407c31)
17:46:14:337	1>Target: x86_64-pc-windows-msvc
17:46:14:337	1>Thread model: posix
17:46:14:337	1>InstalledDir: D:\Projetos\LLVMs\iz-llvm\install-llvm\bin
17:46:28:385	1>clang-cl : message : diagnostic msg:
```

Source of `?CityMurmur@CityHash@@YA?AU_uint128@1@PEBDIU21@@Z`

```
    // A subroutine for CityHash128().  Returns a decent 128-bit hash for strings
    // of any length representable in signed long.  Based on City and Murmur.
    static uint128 CityMurmur(const char* s, size_t len, uint128 seed) {
        uint64 a = Uint128Low64(seed);
        uint64 b = Uint128High64(seed);
        uint64 c = 0;
        uint64 d = 0;
        signed long l = len - 16;
        if (l <= 0) {  // len <= 16
            a = ShiftMix(a * k1) * k1;
            c = b * k1 + HashLen0to16(s, len);
            d = ShiftMix(a + (len >= 8 ? Fetch64(s) : c));
        }
        else {  // len > 16
            c = HashLen16(Fetch64(s + len - 8) + k1, a);
            d = HashLen16(b + len, c + Fetch64(s + len - 16));
            a += d;
            do {
                a ^= ShiftMix(Fetch64(s) * k1) * k1;
                a *= k1;
                b ^= a;
                c ^= ShiftMix(Fetch64(s + 8) * k1) * k1;
                c *= k1;
                d ^= c;
                s += 16;
                l -= 16;
            } while (l > 0);
        }
        a = HashLen16(a, c);
        b = HashLen16(d, b);

        uint128 result;
        result.first = (uint64)(a ^ b);
        result.second = (uint64)(HashLen16(b, a));
        return result;
    }
```

**Comment by Naville** [comment] 2023-04-03 01:58
Duplicate of #51

**Closed** 2023-04-03 11:26 UTC
Labels: duplicate
